### ISSUE TITLE
建议空闲教室不限于“今日”和当日的“未来时间”

### ISSUE THREAD

**Issue by jwhsir** [pkuhelper-web/imasugu#2]
如题，目前空闲教室功能在时间范围上有两个限制：（1）当天内，只能查看“未来”时间，比如下午查询就只能查到下午+晚上，早上的没法回顾，尽管可以理解这样的设计，但保留早上的可能更好，在不影响使用的情况下满足更多需求；（2）只能查看今日，无法查看未来几天的教室空闲情况。

如果能改进就最好了，非常感谢！！！

**Comment by xmcp** [comment]
正如<ruby>其名<rt>いますぐ</rt></ruby>，“空闲教室”的设计初衷是portal那个空闲教室页面用起来过于繁琐，要做一个尽可能快速地找到可以自习的教室的工具。
“空闲教室”的使用流程是紧紧围绕着这个目标设计的，因此只显示从现在开始的大约6节课（正常手机屏幕尺寸）。我认为，显示“明天的教室情况”或“过去的教室情况”对这个目标无益。

如果你不是要“找一个现在可以去自习的地方”，建议使用portal上的空闲教室功能。

**Comment by xmcp** [comment]
“空闲教室”今后可能会覆盖更多的应用场景，但我目前没觉得有这样的必要。

**Comment by jwhsir** [comment]
理解了，感谢！总体上的确这样更方便，也更直观，我也就是提个小建议。请继续开发/维护这样实用的工具！
